spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testhibernate
    username: root
    password: 201408020

  security:
    user:
      name: abulfet
      password: 12345

server:
  port: 8089

