spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hibrenatedb
    username: root
    password: 201408020



#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
#

server:
  port: 8088